### ISSUE TITLE
cmd/cue: cue fmt fails with unresolved import with packageless cue file

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#3329]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.10.0-alpha.2
</pre>

### Does this issue reproduce with the latest stable release?

Yes (v0.9.2)

### What did you do?

```
exec cue fmt ./...
-- cue.mod/module.cue --
module: "cue.example/foo"
language: {
	version: "v0.9.0"
}
-- bar/apply_set_list.cue --
package bar

-- bar/list.cue --
import "cue.example/foo/bar"

bar
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> exec cue fmt ./...
[stderr]
cue.example/foo/bar@v0: import failed: no dependency found for package "cue.example/foo/bar":
    ./bar/list.cue:1:8
[exit status 1]
FAIL: /tmp/testscript2600822160/z.txtar/script.txtar:1: unexpected command failure
```

Thanks to @uhthomas for the report.

**Comment by mvdan** [comment]
I bisected this to https://review.gerrithub.io/c/cue-lang/cue/+/1194124, cc @NoamTD. I think we only want to treat package loading errors as fatal if they're for the package arguments given on the command line, but if they belong to any of the parsed files, they should continue being ignored.

**Comment by mvdan** [comment]
This is a relatively recent regression, as the above worked on v0.8.2 and started failing on v0.9.0, so I'll look into a fix soon.
